name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      -  complited

jobs:

  build:

    runs-on: self-hostes

    steps:
    - name: Pull docker image
      run: sudo docker pull danylotrofymov/psycological-help-fe:latest
    - name: Delete old container
      run: docker rm -f psycological-help-container || true
    - name: Run new container
      run: docker run -d -p 3000:3000 --name psycological-help-container danylotrofymov/psycological-help-fe
    
