name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      -  complited

jobs:

  build:

    runs-on: self-hostes

    steps:
    - name: Pull docker image
      run: sudo docker pull danylotrofymov/psychological-help-fe:latest
    - name: Delete old container
      run: docker rm -f psychological-help-container || true
    - name: Run new container
      run: docker run -d -p 3000:3000 --name psychological-help-container danylotrofymov/psychological-help-fe
    
